//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Data
{
    using QLBHDT.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon : BaseViewModel
    {
        private string mahd;
        public string MaHD { get => mahd; set { mahd = value; OnpPropertychanged(); } }
        private string makh;
        public string MaKH { get => makh; set { makh = value; OnpPropertychanged(); } }
        private string masp;
        public string MaSP { get => masp; set { masp = value; OnpPropertychanged(); } }
        private Nullable<System.DateTime> ngayhd;
        public Nullable<System.DateTime> NgayHD { get => ngayhd; set { ngayhd = value; OnpPropertychanged(); } }
        private Nullable<double> soluong;
        public Nullable<double> SoLuong { get => soluong; set { soluong = value; OnpPropertychanged(); } }
        private Nullable<double> trigia;
        public Nullable<double> TriGia { get => trigia; set { trigia = value; OnpPropertychanged(); } }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
