//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Data
{
    using QLBHDT.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.QLNDs = new HashSet<QLND>();
        }

        private string makh;
        public string MaKH { get => makh; set { makh = value; OnpPropertychanged(); } }
        private string hoten;
        public string HoTen { get => hoten; set { hoten = value; OnpPropertychanged(); } }
        private string diachi;
        public string DiaChi { get => diachi; set { diachi = value; OnpPropertychanged(); } }
        private string sdt;
        public string SDT { get => sdt; set { sdt = value; OnpPropertychanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QLND> QLNDs { get; set; }
    }
}
