//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Data
{
    using QLBHDT.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class QLND : BaseViewModel
    {
        private string taikhoan;
        public string TaiKhoan { get => taikhoan; set { taikhoan = value; OnpPropertychanged(); } }
        private string matkhau;
        public string MatKhau { get => matkhau; set { matkhau = value; OnpPropertychanged(); } }
        private string makh;
        public string MaKH { get => makh; set { makh = value; OnpPropertychanged(); } }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
