//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHDT.Data
{
    using QLBHDT.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }

        private string masp;
        public string MaSP { get => masp; set { masp = value; OnpPropertychanged(); } }
        private string tensp;
        public string TenSP { get => tensp; set { tensp = value; OnpPropertychanged(); } }
        private string nuocsx;
        public string NuocSX { get => nuocsx; set { nuocsx = value; OnpPropertychanged(); } }
        private Nullable<double> gia;
        public Nullable<double> Gia { get => gia; set { gia = value; OnpPropertychanged(); } }
        private Nullable<double> soluong;
        public Nullable<double> SoLuong { get => soluong; set { soluong = value; OnpPropertychanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
